#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'erbcop'
require 'templatecop'

Templatecop::Cli.call(
  default_configuration_path: File.expand_path('../default.yml', __dir__),
  default_path_patterns: %w[**/*.erb],
  executable_name: 'erbcop',
  implicit_configuration_paths: %w[.erbcop.yml .rubocop.yml],
  ruby_extractor: Erbcop::RubyExtractor
)

